# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_remove_vote_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='current_status',
            field=models.CharField(choices=[('todo', 'todo'), ('doing', 'doing'), ('done', 'done')], default='todo', max_length=5),
        ),
    ]
