# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='FRPost',
        ),
        migrations.RenameModel(
            old_name='Vote',
            new_name='FRVote',
        ),
    ]
